{"name": "Attempted login with invalid credentials and some empty data -- @1.1 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1717323180367, "stop": 1717323189024}, {"name": "When I fill in \"username\" with \"standard\"", "status": "passed", "start": 1717323189024, "stop": 1717323189134}, {"name": "And I fill in \"Password\" with \"bond123\"", "status": "passed", "start": 1717323189134, "stop": 1717323189230}, {"name": "And I press \"Login\"", "status": "passed", "start": 1717323189230, "stop": 1717323189289}, {"name": "Then I should see the error message \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1717323189289, "stop": 1717323189312}], "parameters": [{"name": "username", "value": "standard"}, {"name": "password", "value": "bond123"}, {"name": "error_message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1717323180366, "stop": 1717323191389, "uuid": "2b1d3c16-e2ca-4672-b74f-37b8a08d1fac", "historyId": "e4e07f965ff3ff7611db0ca73a884ac0", "fullName": "Login: Attempted login with invalid credentials and some empty data", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}