{"name": "Attempted login with invalid credentials and some empty data -- @1.5 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1717323224369, "stop": 1717323233183}, {"name": "When I fill in \"username\" with \"standard_bond\"", "status": "passed", "start": 1717323233183, "stop": 1717323233366}, {"name": "And I fill in \"Password\" with \"secret_sauce\"", "status": "passed", "start": 1717323233366, "stop": 1717323233490}, {"name": "And I press \"Login\"", "status": "passed", "start": 1717323233490, "stop": 1717323233549}, {"name": "Then I should see the error message \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1717323233549, "stop": 1717323233574}], "parameters": [{"name": "username", "value": "standard_bond"}, {"name": "password", "value": "secret_sauce"}, {"name": "error_message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1717323224368, "stop": 1717323235704, "uuid": "5a42389c-a0e5-4340-8243-dce689214a65", "historyId": "ca6d95f68fcb5a2589c059b897fcd5eb", "fullName": "Login: Attempted login with invalid credentials and some empty data", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}